/*
 * This Java source file was generated by the Gradle 'init' task.
 */

import org.junit.Test;

import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.RepeatedTest;

import java.util.*;

public class LibraryTest {
    int[][] weeklyMonthTemperatures = {
            {66, 64, 58, 65, 71, 57, 60},
            {57, 65, 65, 70, 72, 65, 51},
            {55, 54, 60, 53, 59, 57, 61},
            {65, 56, 55, 52, 55, 62, 57}};

    @RepeatedTest(5)
    @DisplayName("Arrays Of Arrays")
    public void testArraysOfArrays() {
        int[] arrTest = {66, 64, 58, 65, 71, 57, 60};
        Assertions.assertEquals(arrTest,
                Library.lowestAverage(weeklyMonthTemperatures),
                "Arrays Of Arrays");
    }

    /********Lab03*********/

    @Test
    public void testWeatherData() {
        Assertions.assertEquals(
                "Never saw temperature: 63\n" +
                        "Never saw temperature: 67\n" +
                        "Never saw temperature: 68\n" +
                        "Never saw temperature: 69\n",
                Library.weatherData(weeklyMonthTemperatures));
    }

    @Test
    public void testTally() {
        List<String> votes = new ArrayList<>();
        votes.add("Bush");
        votes.add("Bush");
        votes.add("Bush");
        votes.add("Shrub");
        votes.add("Hedge");
        votes.add("Shrub");
        votes.add("Bush");
        votes.add("Hedge");
        votes.add("Bush");
        Assertions.assertEquals(
                "Bush",
                Library.tally(votes)
        );
    }

    @Test
    public void testTallyNull() {
        List<String> vote = new ArrayList<>();
        Assertions.assertEquals(
                "No Winner!",
                Library.tally(vote)
        );
    }

}
