/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.junit.Test;
import static org.junit.Assert.*;

import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.RepeatedTest;

public class LibraryTest {
    @Test public void testSomeLibraryMethod() {
        Library classUnderTest = new Library();
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }

    @RepeatedTest(5)
  @DisplayName("Arrays Of Arrays")
  public void testArraysOfArrays() {
    int[][] testWeeklyMonthTemperatures = {
        {66, 64, 58, 65, 71, 57, 60},
        {57, 65, 65, 70, 72, 65, 51},
        {55, 54, 60, 53, 59, 57, 61},
        {65, 56, 55, 52, 55, 62, 57}};
    int [] arrTest = {66, 64, 58, 65, 71, 57, 60};

    Assertions.assertEquals(arrTest,
        classUnderTest.arraysOfArrays(testWeeklyMonthTemperatures),
        "Arrays Of Arrays");
  }
}
