import classes.Restaurant;
import classes.Review;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class Library {
    public static void main(String[] args) {
        //Restaurant
        Restaurant testRes = new Restaurant("Burger", 262.22);
        //Review
        Review testRev = new Review("Not Good", "Noor", 0);

        //Print Restaurant
        System.out.println("Name: " + testRes.getName());
        System.out.println();
        System.out.println("Price: " + testRes.getPrice());
        System.out.println();
        System.out.println("Star: " + testRes.getStar());
        System.out.println();
//        System.out.println("Review: " + testRes.addReview(testRev));
        System.out.println();
        System.out.println("The Class: " + testRes);
        System.out.println();

        //Print Review

        System.out.println("Name: " + testRev.getAuthor());
        System.out.println();
        System.out.println("Body: " + testRev.getBody());
        System.out.println();
        System.out.println("Star: " + testRev.getStars());
        System.out.println();
        System.out.println("The Class: " + testRev);
        System.out.println();
    }
}
