/*
 * This Java source file was generated by the Gradle 'init' task.
 */

import org.junit.Test;

import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;

import static org.junit.Assert.*;

public class AppTest {
    @Test
    public void testTally_TieForWinner() throws IOException {
        FileReader filePath = new FileReader("src/main/resources/gates.js");
        assertEquals(
                "Not Expected Result \n",
                "Missing Semicolon at Line: 1\n" +
                        "Missing Semicolon at Line: 2\n" +
                        "Missing Semicolon at Line: 3\n" +
                        "Missing Semicolon at Line: 4\n" +
                        "Missing Semicolon at Line: 5\n" +
                        "Missing Semicolon at Line: 6\n" +
                        "Missing Semicolon at Line: 7\n" +
                        "Missing Semicolon at Line: 8\n" +
                        "Missing Semicolon at Line: 9\n" +
                        "Missing Semicolon at Line: 10\n",
                App.readingFile(filePath)
        );
    }

    @Test
    public void testAppHasAGreeting() throws IOException {
        FileReader filePath = new FileReader("src/main/resources/gates.js");
        assertNotNull("app should have output", App.readingFile(filePath));
    }
}
