/*
 * This Java source file was generated by the Gradle 'init' task.
 */

import classes.Restaurant;
import classes.Review;
import org.junit.Test;

import static org.junit.Assert.*;

public class LibraryTest {
    Restaurant testRes = new Restaurant("Burger", 262.2);
    Review testRev = new Review("Great!", "Noor", 5);

    @Test
    public void ResMethods() {
        //Restaurant Object before Insertion, toStringTest
        assertEquals("Restaurant Object before Insertion failed",
                "Restaurant{name='Burger', priceCategory=262.2$\n" +
                        ", Number of reviews=[]\n" +
                        ", Rate=0}", String.valueOf(testRes));

        //getName()
        assertEquals("Getting the name failed",
                "Burger",
                testRes.getName());

        //getPriceCategory()
        assertEquals("getPriceCategory failed",
                testRes.getPriceCategory(),
                "262.2$");

        //getReview() before adding review
        assertEquals("getReview failed",
                String.valueOf(testRes.getReview()),
                "[]");

        //checkStars before adding review
        assertEquals("checkStars before adding review failed",
                testRes.checkStars(),
                0);

        //addReview
        testRes.addReview(testRev);

        //getReview() after adding review
        assertEquals("getReview() after adding review failed",
                String.valueOf(testRes.getReview()),
                "[Review{, body='Great!', author='Noor', stars='5'}]");

        //checkStars() after the first review
        assertEquals("checkStars() after the first review failed",
                testRes.checkStars(),
                5);

        //Restaurant Object after Insertion, toStringTest
        assertEquals("Restaurant{name='Burger', priceCategory=262.2$\n" +
                ", Number of reviews=[Review{, body='Great!', author='Noor', stars='5'}]\n" +
                ", Rate=5}", String.valueOf(testRes));
    }

    /************/

    @Test
    public void RevMethods() {
        //getAuthor()
        assertEquals("Noor", testRev.getAuthor());

        //getBody()
        assertEquals("getBody() failed", testRev.getBody(), "Great!");

        //getStars()
        assertEquals("getStars() failed",
                testRev.getStars(),
                5);

        //toStringTest
        assertEquals("Review{, body='Great!', author='Noor', stars='5'}",
                String.valueOf(testRev));
    }

}
