/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import classes.Restaurant;
import org.junit.Test;
import static org.junit.Assert.*;

public class LibraryTest {
    Restaurant testRes= new Restaurant("Burger", 262.22);

    @Test
    public void ResGetters() {
        assertEquals("Burger", testRes.getName());
        assertEquals(262.22, testRes.getPrice(),262.22);
        assertEquals(1, testRes.getStar());
    }
    @Test
    public void toStringTest() {
        assertEquals("Error in To String",
                "Restaurant{name='Burger', stars=1, price=262.22$}"
                , testRes.toString());

    }
}
