/*
 * This Java source file was generated by the Gradle 'init' task.
 */

import java.io.*;

public class App {

    public static String readingFile(FileReader path) throws IOException {
        BufferedReader reader = new BufferedReader(path);
        StringBuilder returnedVal = new StringBuilder();
        int count = 0;
        while (reader.readLine() != null) {
            if ((!reader.readLine().endsWith(";"))
                    && (!reader.readLine().endsWith("{"))
                    && (!reader.readLine().endsWith("}"))
                    && (!reader.readLine().contains("if"))
                    && (!reader.readLine().contains("else"))) {
                returnedVal.append("Missing Semicolon at Line: ").append(++count).append("\n");
            }
        }
        return returnedVal.toString();
    }

    public static void main(String[] args) throws IOException {
        FileReader filePath = new FileReader("src/main/resources/gates.js");
        System.out.println(readingFile(filePath));
    }
}
